# Generated by Django 3.1.7 on 2021-06-24 09:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0002_auto_20210322_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='fileUpload/')),
            ],
        ),
        migrations.CreateModel(
            name='LogPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Пользователь')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('date', models.DateTimeField(verbose_name='Дата зачисления')),
                ('poll', models.CharField(max_length=255, verbose_name='Опрос')),
                ('add', models.BooleanField(null=True, verbose_name='Зачисление')),
            ],
            options={
                'verbose_name': 'Логи зачисления баллов',
                'verbose_name_plural': 'Логи зачисления баллов',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NumComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер компетенции')),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=510, verbose_name='Описание')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('points', models.IntegerField(default=10, verbose_name='Баллы')),
                ('latePosting', models.BooleanField(default=False, verbose_name='Отложная публикация?')),
                ('datePosting', models.DateTimeField(default=datetime.datetime(2021, 6, 24, 12, 50, 16, 367681), verbose_name='Дата и время публикации')),
                ('in_archive', models.BooleanField(default=False, verbose_name='Архивный опрос?')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='PollsCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.polls', verbose_name='Опрос')),
                ('poll_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.profile', verbose_name='Кого оценили')),
                ('user_valuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ids', to='model.profile', verbose_name='Оценщик')),
            ],
            options={
                'verbose_name': 'Пройденный опрос',
                'verbose_name_plural': 'Пройденные опросы',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.polls')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='SessionTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_session', models.IntegerField(default=0, unique=True, verbose_name='Номер смены')),
                ('name_session', models.CharField(default='Смена не определена', max_length=50, unique=True, verbose_name='Название смены')),
                ('date_from_session', models.DateField(blank=True, null=True, verbose_name='Дата начала смены')),
                ('date_to_session', models.DateField(blank=True, null=True, verbose_name='Дата конца смены')),
                ('active_session', models.BooleanField(default=False, null=True, verbose_name='Активная смена')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['number_session'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок теста')),
                ('description', models.TextField(verbose_name='Описание теста')),
                ('points', models.IntegerField(verbose_name='Баллы за прохождение')),
                ('latePosting', models.BooleanField(default=False, verbose_name='Отложная публикация?')),
                ('in_archive', models.BooleanField(default=False, verbose_name='Архивный опрос?')),
                ('num_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Компетенция', to='model.numcomp', to_field='number')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Смена', to='model.sessiontc', to_field='number_session')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='RatingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('rating', models.IntegerField(default=100000, verbose_name='Рейтинг')),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Сессия', to='model.sessiontc', to_field='number_session')),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Команда', to='model.team', to_field='name')),
            ],
            options={
                'verbose_name': 'Рейтинг команды',
                'verbose_name_plural': 'Рейтинг команды',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('rating', models.IntegerField(default=100000, verbose_name='Рейтинг')),
                ('username', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Пользователь', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинг',
            },
        ),
        migrations.CreateModel(
            name='QuestionsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Тест', to='model.test')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='QuestionsCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.polls', verbose_name='Опрос')),
                ('poll_check', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='model.pollscheck', verbose_name='ID пройденного опроса')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.questions', verbose_name='Вопрос')),
                ('user_valuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.profile', verbose_name='Оценщик')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
        migrations.AddField(
            model_name='polls',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.sessiontc', to_field='number_session'),
        ),
        migrations.CreateModel(
            name='AnswersTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Вопрос', to='model.questionstest')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.sessiontc', to_field='number_session'),
        ),
    ]
