# Generated by Django 3.1.7 on 2021-06-25 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20210624_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пользователь', to='model.profile')),
            ],
            options={
                'verbose_name': 'Пройденный тест',
                'verbose_name_plural': 'Пройденные тесты',
            },
        ),
        migrations.AlterField(
            model_name='polls',
            name='datePosting',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 18, 41, 57, 235102), verbose_name='Дата и время публикации'),
        ),
        migrations.CreateModel(
            name='QuestionsCheckTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ')),
                ('point', models.IntegerField(default=0, verbose_name='Points')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.test', verbose_name='Test')),
                ('poll_check', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='model.checktest', verbose_name='ID пройденного теста')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.questionstest', verbose_name='Вопрос')),
                ('user_valuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.profile', verbose_name='Оценщик')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
    ]
