# Generated by Django 3.1.7 on 2021-07-05 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20210625_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerstest',
            options={'verbose_name': 'Ответ на тест', 'verbose_name_plural': 'Ответы на тест'},
        ),
        migrations.AlterModelOptions(
            name='questionschecktest',
            options={'verbose_name': 'Ответ на вопрос Теста', 'verbose_name_plural': 'Ответы на вопросы Теста'},
        ),
        migrations.AlterModelOptions(
            name='questionstest',
            options={'verbose_name': 'Вопрос на тест', 'verbose_name_plural': 'Вопросы на тест'},
        ),
        migrations.AlterField(
            model_name='answerstest',
            name='answer',
            field=models.CharField(max_length=4000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='logpoint',
            name='poll',
            field=models.CharField(max_length=2505, verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='category',
            field=models.CharField(max_length=1000, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='datePosting',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 14, 32, 28, 120764), verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='description',
            field=models.CharField(max_length=5100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='title',
            field=models.CharField(max_length=2505, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=2505, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=2505, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questionscheck',
            name='answer',
            field=models.CharField(max_length=1000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questionschecktest',
            name='answer',
            field=models.CharField(max_length=3000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questionstest',
            name='question',
            field=models.CharField(max_length=3055, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='sessiontc',
            name='name_session',
            field=models.CharField(default='Смена не определена', max_length=500, unique=True, verbose_name='Название смены'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=3055, verbose_name='Заголовок теста'),
        ),
    ]
